export enum Events {
  DOMSnapshot = "domSnapshot",
  VisualSnapshot = "visualSnapshot",
  Command = "command",
  CommandSuccess = "command:success",
  CommandFail = "command:fail",
  CommandEnd = "command:end",
  Session = "session",
  SessionSuccess = "session:success",
  SessionFail = "session:fail",
  SessionEnd = "session:end",
  FindElement = "findElement",
  FindElementSuccess = "findElement:success",
  FindElementFail = "findElement:fail",
  FindElementFromElement = "findElementFromElement",
  FindElementFromElementSuccess = "findElementFromElement:success",
  FindElementFromElementFail = "findElementFromElement:fail",
  FindElements = "findElements",
  FindElementsSuccess = "findElements:success",
  FindElementsFail = "findElements:fail",
  FindElementsFromElement = "findElementsFromElement",
  FindElementsFromElementSuccess = "findElementsFromElement:success",
  FindElementsFromElementFail = "findElementsFromElement:fail",
}
